name: PR Cleanup

# Trigger on pull request closed events (merge and closed)
on:
  pull_request:
    types: [ closed ]

jobs:
  delete_environment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/github-actions
    steps:
      - uses: actions/checkout@v2
        with: 
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22'
        
        # Dependencies to run this script. Use npm to save time.
      - name: Install GitHub Actions script dependencies
        run: npm install

        # Run the script
      - name: Delete Environment
        run: npx ts-node ./pr-cleanup.ts
        env: 
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
